config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'tweets#index'
  get 'tweets' => 'tweets#index'
  get 'tweets/new' => 'tweets#new'
  post 'tweets' => 'tweets#create'
  delete 'tweets/:id' => 'tweets#destroy'
  patch 'tweets/:id' => 'tweets#update'
  get 'tweets/:id/edit' => 'tweets#edit'
  get 'users/:user_id' => 'users#show'
  get 'tweets/:id' => 'tweets#show'
  post 'likes/:tweet_id' => 'likes#like', as: 'like'
  delete 'likes/:tweet_id' => 'likes#unlike', as: 'unlike'

 

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :tweet

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	has_many :likes
	def liked_by? user
		likes.where(user_id: user.id).exists?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  def move_to_index
	redirect_to action: "index" unless user_signed_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!

	def like 
		@tweet = Tweet.find(params[:tweet_id])
		@like = current_user.likes.create(tweet: @tweet)
	end
	def unlike
		@like = current_user.likes.find_by!(tweet_id: params[:tweet_id])
		@like.destroy
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :move_to_index, except: :index
	def index
		@tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
	end

	def new
	
	end

	def create
		Tweet.create(image: tweet_params[:image], text: tweet_params[:text],user_id: current_user.id)

	end

	def destroy
		tweet = Tweet.find(params[:id])
		tweet.destroy if tweet.user_id = current_user.id
	end

	def edit
		@tweet = Tweet.find(params[:id])
	end

	def update
		tweet = Tweet.find(params[:id])
		tweet.update(tweet_params) if tweet.user_id == current_user.id
	end

	def show
		@tweet = Tweet.find(params[:id])
	end

	private
	def tweet_params
		params.permit(:name, :image, :text, :user_id)
	end

	def move_to_index
		redirect_to action: "index" unless user_signed_in?
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@username = current_user.username
  	@tweets = current_user.tweets.page(params[:page]).per(5).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet_app2</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Tweet_app2</a></h1>
          <% if user_signed_in?%>
            <div class="user_nav grid-6">
              <span><%=current_user.username %>
                <ul class="user__info">
                  <li>
                    <a href="/users/<%= current_user.id %>">マイページ</a>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </span>
                  <a class="post" href="/tweets/new">投稿する</a>
            </div>
          <% else %>
            <div class="grid-6">
              <%= link_to "ログイン", new_user_session_path, class: 'post' %>
              <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
            </div>
          <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright Ryhei Kurisaki 2017@temona.
      </p>
    </footer>
  </body>
</html>

app/views/likes/like.html.erb
<div class="contents row">
	<div class="success">
		<h3>
			いいね！しました。
		</h3>
		<a class="btn" href="/tweets">投稿一覧へ戻る</a>
	</div>
</div>

app/views/likes/unlike.html.erb
<div class="contents row">
	<div class="success">
		<h3>
			いいね！を取り消しました。
		</h3>
		<a class="btn" href="/">投稿一覧へ戻る</a>
	</div>
</div>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);"> 
        <div class="more">
          <span><%= image_tag 'arrow_top.png' %></span>
          <ul class="more_list">
              <li>
                <%= link_to '詳細',"/tweets/#{tweet.id}", method: :get %>
              </li>
              <%if user_signed_in? && current_user.id == tweet.id%>
                <li>
                  <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
                </li>
                <li>
                  <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
                </li>
              <% end %>
          </ul>
        </div>
        <%= simple_format(tweet.text) %>
         <span class="name">
              <% if  user_signed_in? && tweet.liked_by?(current_user) %>
               <%= link_to like_path(tweet.id), method: :delete do %>
                 <i class="fa fa-heart fa-2x" aria-hidden="true"></i>
                <% end %>
              <% else %>
                <%= link_to like_path(tweet.id), method: :post do %>
                 <i class="fa fa-heart-o fa-2x" aria-hidden="true"></i>
                <% end %>
              <% end %> 
         
            <a href="/users/<%= tweet.user_id %>">
              <span>投稿者</span><%= tweet.user.username %>
            </a>
          </span>
           
</div>

app/views/tweets/create.html.erb
<div class="contents row">
	<div class="success">
		<h3>
			投稿が完了しました。
		</h3>
		<a class="btn" href="/tweets">投稿一覧へ戻る</a>
	</div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
	<div class="success">
		<h3>
			削除が完了しました。
		</h3>
		<a class="btn" href="/">投稿一覧へ戻る</a>
	</div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
	<%= form_tag('/tweets/#{@tweet.id}',method: :post) do %>
		<h3>
			編集する
		</h3>
		<input placeholder="Image Url" type="text" name="image" value="<%= @tweet.image%>" autofocus= "true">
		<textarea cols="30" name="text" placeholder="text" rows="10"><%= @tweet.text%></textarea>
		<input type="submit" value="SENT">
	<% end %>
</div>

app/views/tweets/index.html.erb
 <div class="contents row">
  <% @tweets.each do |tweet| %>
        <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
	<%= form_tag('/tweets', method: :post) do %>
		<h3>
			投稿する
		</h3>
		<input placeholder="Image Url" type="text" name="image">
    	<textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
    <input type="submit" value="SENT">
	<% end %>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
        <li>
          <%= link_to '戻る', "/", method: :get %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.username %>
      </a>
    </span>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
	<div class="success">
		<h3>
			更新が完了しました。
		</h3>
		<a class="btn" href="/">投稿一覧へ戻る</a>
	</div>
</div>

app/views/users/show.html.erb
<div class="contents row" >
    <p><%= @username %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
     <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
    <% end %>
    <%= paginate(@tweets) %>
 </div>